### ISSUE TITLE
New Scraper: Development Authority of Fulton County (DAFC)

### ISSUE THREAD

**Issue by jpt-c** [City-Bureau/city-scrapers-atl#19]
Create a new scraper for Development Authority of Fulton County (DAFC)

Website: https://www.developfultoncounty.com/meetings-and-minutes.php#tefra 
Jurisdiction: Fulton County
Classification: Development
the DAFC provides wide-ranging economic development services on behalf of Fulton County. DAFC also facilitates community based economic development initiatives.

**Comment by rhetr** [comment]
should the JDAMA meetings also be included?

**Comment by jpt-c** [comment]
Just took a look, and yeah I think it'd be good to assuming it doesn't make things much more complex.
