### ISSUE TITLE
New Scraper: Atlanta BeltLine Affordable Housing Advisory Board (BAHAB)

### ISSUE THREAD

**Issue by jpt-c** [City-Bureau/city-scrapers-atl#29]
Create a new scraper for Atlanta BeltLine Affordable Housing Advisory Board (BAHAB)

Website: https://beltline.org/the-project/planning-and-community-engagement/bahab/#meetings-amp-agendas 
Jurisdiction: City of Atlanta
Classification: Housing, Development
Its primary function is to advise on the administration and execution of the BeltLine Affordable Housing Trust Fund (BAHTF).

BAHAB’s Role and Responsibilities
Making recommendations to Invest Atlanta and the City on goals and policies for the use of BAHTF dollars
Monitoring the location and availability of affordable housing throughout the BeltLine
Coordinating the activities of BAHAB with other affordable housing throughout the BeltLine

**Comment by rhetr** [comment]
resolved with #133
