### ISSUE TITLE
New Scraper: Atlanta BeltLine Inc.

### ISSUE THREAD

**Issue by jpt-c** [City-Bureau/city-scrapers-atl#5]
Create a new scraper for Atlanta BeltLine Inc.

Website: https://beltline.org/events/category/community-meetings/public-meetings/list/ 
Jurisdiction: City of Atlanta
Classification: Development, Housing, Transportation

**Comment by rhetr** [comment]
this uses the 'tribe' events calendar like what @s-j-b and i have mentioned before: https://beltline.org/wp-json/tribe/events/v1/events

i think we should write a mixin utilizing the events calendar api, which all wordpress sites utilizing this calendar would be able to benefit from. i can get started on this if we want.

**Comment by rhetr** [comment]
here's a list of all the different possible event types:

https://beltline.org/wp-json/tribe/events/v1/categories

here are the category mappings that make sense to me, i can change them if something else makes more sense:

### `BOARD`
abi-board-meetings
abi-executive-committee-meetings
leadership

### `HOUSING`
housing
bahab-meetings

### `FORUM`
community-meetings
economic-development

### `ADVISORY_COMMITTEE`
design-review-committee

### `NOT_CLASSIFIED`
aerobics
art-on-atlanta-beltline
artist-meetings
atlanta-beltline-tours
beltline-live-stream
biking
boot-camp
fitness
farmers-market
grand-openings
ground-breakings
health-and-fitness
hiking
home-buyer-workshop
home-empower-workshops
home-fix-it-series

do we even want to include all the `NOT_CLASSIFIED` events, or should i just drop them?

**Comment by jamesturk** [comment]
If the data from the other two is coming through in this then I'd say this covers #29 and #30 too.

I do think those NOT_CLASSIFIED are Ok to drop

**Comment by rhetr** [comment]
resolved with #133

**Comment by jpt-c** [comment]
Definitely, sounds like a great idea.
