### ISSUE TITLE
New Scraper: Fulton-DeKalb Hospital Authority (Grady Health System)

### ISSUE THREAD

**Issue by ghost** [City-Bureau/city-scrapers-atl#56]
Create a new scraper for Fulton-DeKalb Hospital Authority (Grady Health System)

Website: https://www.dekalbcountyga.gov/meeting-calendar 
Jurisdiction: Georgia
Classification: Public Health
versight of the Grady Memorial Hospital Corporation, a 17 member non-profit Board of Directors charged with administering the Grady Health System, sponsoring community health events, and advocating for solid healthcare policy in the State of Georgia. (https://dekalbcountyga.granicus.com/boards/w/968f9572ef2211df/boards/7144)

**Comment by rhetr** [comment]
my bad, i opened a PR for this but i haven't finished writing tests or the location/links part of the scraper yet
