### ISSUE TITLE
New Scraper: Atlanta Board of Education

### ISSUE THREAD

**Issue by jpt-c** [City-Bureau/city-scrapers-atl#6]
Create a new scraper for Atlanta Board of Education

Website: https://www.atlantapublicschools.us/apsboard https://www.atlantapublicschools.us/Page/17673#calendar17299/20220726/month
Jurisdiction: City of Atlanta
Classification: Education

**Comment by rhetr** [comment]
could make sense to use this ical: https://www.atlantapublicschools.us/site/handlers/icalfeed.ashx?MIID=17299

**Comment by rhetr** [comment]
some notes:

- ical is a hassle and doesn't provide any benefit over scraping regularly
- this is a Blackboard site that uses ASPX; the controller can be queried directly to get calendar events. adapted from the source:

```javascript
$.ajax({
    type: "POST",
    url: "https://www.atlantapublicschools.us/site/UserControls/
          Calendar/CalendarController.aspx/GetEvents",
    data: "{ModuleInstanceID: 17299, StartDate: '08/27/2022', EndDate: '12/31/2022'}",
    contentType: "application/json; charset=utf-8",
    dataType: "json",
    cache: false,
    success: function(result) {
            var calevents = eval(result.d);
            console.log(calevents);
    }
});
```
doesn't seem necessary but just wanted to document it.

- there is also a separate website containing the agenda, currently only of the next upcoming meeting. afaik it doesn't have e.g. a common ID that can be easily used to fetch the agenda. also uses javascript https://simbli.eboardsolutions.com/SB_Meetings/ViewMeeting.aspx?S=36031014&MID=104070
