### ISSUE TITLE
New Scraper: Atlanta Citizen Review Board

### ISSUE THREAD

**Issue by jpt-c** [City-Bureau/city-scrapers-atl#7]
Create a new scraper for Atlanta Citizen Review Board

Website: https://acrbgov.org/ 
Jurisdiction: City of Atlanta
Classification: Policing
to provide citizen oversight of misconduct accusations against sworn members of the police and corrections departments in the City of Atlanta.

**Comment by rhetr** [comment]
what should this be classified as? `POLICE BEAT` or something else? https://cityscrapers.org/docs/development/#classifications

**Comment by jpt-c** [comment]
I think it best fits ADVISORY_COMMITTEE?
